### ISSUE TITLE
Vorstand  - navigationspunkt umbenennen (PH)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#11]
denke das darf nicht so lauten, sondern muss in  'Abteilungsleitung'  umbenannt werden  , da Vorstand nur im Hauptverein

**Comment by AlexanderPraegla** [comment]
Aber trotzdem laden sie immer zur Vorstandssitzung ein 😜

**Comment by AlexanderPraegla** [comment]
✔️
