### ISSUE TITLE
Vorschlag1 (Test: PC)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#2]
Hallo Alex, erstmal: Großartige Arbeit soweit, ich schreib hier mal meine Gedanken nieder und hoffe du weißt, dass ich trotz jeden einzelnen Vorschlags sehr begeistert von der bereits existierenden Version bin :) 

1) bei den Mannschaftsprofilen kann man ja bei Info> Zur Nuliga - 
dies sollte in den kommenden Reitern >Tabelle, >Spielplan auch möglich sein, da 
man dann direkt vom Spielplan zur Nuliga-Version wechseln kann, um sich z.B. kommende
Auswärtshallen direkt anzusehen oder die Gegner in Nuliga aufzurufen. 

2) Es sollte vielleicht noch irgendwo "SpVgg Altenerding Handball" auf der Startseite stehen, damit man weiß, dass man auf unserer Seite ist. Aber das hast du bestimmt eh in Planung. 

3) Ich habe lange Ladezeiten, wenn ich von Bsp >Über uns>Geschichte zu > Mannschaften > Herren 1 springe. Manchmal lädt es auch gar nicht. Kann natürlich auch an mir liegen.

4) Die Website behält offenbar bei, wenn man bei bspw. Herren 1 in >Tabelle ist, dann woanders hin springt (im Test: >Über uns >Geschichte) und dann wieder zurück auf >Herren 1 geht (d.h. dann ist man immer noch im Segment >Tabelle) Falls das so gedacht ist, finde ich es gut, falls nicht, müsstest du es noch fixen. Ist fraglich, was da praktischer ist, immer wieder auf > Info macht wahrscheinlich auch wenig Sinn, also ist es schätzungsweise mal beabsichtigt. 

Mehr Feedback bekommst du gerne, sobald der Login funktioniert, das hab ich bislang nicht geschafft :) 

Liebe Grüße und Danke für deine tolle Arbeit <3
Julius

**Comment by AlexanderPraegla** [comment]
Vielen Dank.

1. Ja das hab ich mir schonmal gedacht, aber ich wusste nicht wie ich das bei den Tabellen am schönsten unter bringe und habe es deshalb erstmal provisorisch bei der Info mit reingeklatscht. Hier hoffe ich auf Feedback von der Petra bzgl. des Designs.

2. Der Plan ist da wo das Bild von der Zeichnung mit den Händen ist, ein Logo einzufügen, in welchem das Vereinslogo, Name und Vereinsfarben enthalten sind.

3. Das Problem mit dem Ladezeiten hab ich jetzt bei mir nicht, müssen wir aber mal beobachten, ob das öfters und regelmäßig auftritt.

4. Das ist kein Bug sondern ein Feature ;) Ne war wirklich so gedacht, da ich es nervig fand bei einem Refresh von der Seite jedes mal erneut den Reiter auszuwählen. Außerdem kann man so z.B. die Tabellen von mehreren Mannschaften einfacher durchschauen.

Login sollte jetzt gehen, gab ein kleines Problem mit den Daten in der Datenbank, was ich jetzt aber gefixed habe :)

Danke für das Feedback.

**Comment by AlexanderPraegla** [comment]
1. Ist Erledigt.
2. Neues Issue abgeleitet um hier zumachen zu können.
3. Wird weiter beobachtet.
4. Ist so gedacht gewesen
