### ISSUE TITLE
Footer / Impressum (PH)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#3]
footer jetzt:  ©2017 Altenerding Handball

mein Vorschlag : © 2017 SpVgg Altenerding e.V. | Abteilung Handball 

Impressum:  
https://www.praegla.net/pinkie/public/legalNotice.xhtml 
Meiner Meinung nach, muss hier der Abteilungsleiter und seine Kontaktdaten und dann der Hinweis dazu: 

Inhaltlich verantwortlich gemäß §10 Absatz 3 MDStV
und das ist dann Jens.   (wenn es so ist)

**Comment by AlexanderPraegla** [comment]
[Done](https://github.com/danielsagert/Pinkie/tree/pinkie-3)
