### ISSUE TITLE
Spielberichte (PH)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#4]
1.  Eingabeseite: Hinweis , was * zu sagen hat = Pflichtfeld  (weiß ja nicht jeder Trainer)
2. Textfeld : würde ich größer machen, denn das kleine Feld ist für den Erfasser zu klein und es geht der Überblick verloren
3. Felder:  Titel und Zusammenfassung  - dahinter maximale Zeichenanzahl angeben (damit einzeilig oder zweizeilig
4. Evtl. Handlungsanweisung für Trainer verfassen, was in welchen Feld zu stehen hat, damit die Überschriften usw. gleich strukturiert sind
5. Braucht es einen 'abbrechen' button, falls der Verfasser doch keinen Beitrag machen möchte?
 Nicht jedem ist denke ich klar, dass er einfach über 'back' oder die Navi rauskommt.
6. Bilder hinzufügen: 
Hochkantfoto wurde einfach querformatig eingefügt? / ist das Bild immer am Ende? Kann der Verfasser dies beeinflussen? / Bild lässt sich im Bearbeitungsmodus nicht mehr löschen? Wie ist dies möglich?
https://www.praegla.net/pinkie/secure/report/reportEdit.xhtml?reportId=1001

7. Übersicht der Spielberichte (Liste) https://www.praegla.net/pinkie/public/news/report.xhtml
Headline: ok
Zusammenfassung: ok
Verfasser:  würde ich nicht grau hinterlegen (wie Headline) und kleinere Schrift. Das ist nicht die wichtige Info auf der Seite. Vielleicht auch den Strich zwischen Zusammenfassung und Verfasser entfernen.

8. Generell:  mir fehlt die Info, wann das Spiel war. Muss das dann der Verfasser mit eingeben? dann muss es in die Handlungsanweisung.  
Im Eingabemodus, wäre am Ende des Textfeldes ein Link cool zur entsprechenden NuLiga  (evtl. über die Auswahl der Mannschaft möglich?) 

9. Freigabeprozess: wer darf hier verfassen und eingeben? und wer online stellen?   (rollenkonzept)

**Comment by AlexanderPraegla** [comment]
1. Hinweis eingefügt
2. Textfeld größer
3. Maximale Zeichenanzahl festgelegt und Tooltip erstellt
4. TBD
5. TBD
6. Button zum entfernen des Bildes eingefügt. Issue mit Hochkantfotos noch offen
7. Schriftgröße des Verfassers verkleinert und graue Hinterlegung entfernt
8. TBD
9. Verfassen dürfen Mitglieder mit der Rolle Presse oder Admin. Ein Freigabeprozess ist bisher nicht geplant da ich davon ausgehe, das die Personen mit diesen Rollen vernünftig genug sind keinen Unsinn anzustellen. Falls doch, Rolle entziehen und dann ggf. über einen Freigabeprozess nachdenken (bedeutet aber wieder mehr Arbeit für die Kathi wenn sie alle Berichte freigeben muss)

Zu Klären:
4. -> Handlungsanweisung erstellen? Titel und Zusammenfassungs Vorgabe?
5. -> Abbrechen Button nötig?
6. -> Hochkant von iPhone macht Probleme
8. -> Soll das Datum vom Spiel selber eingetragen werden können und soll das dann angezeigt werden, oder soll das Datum an dem der Bericht erstellt wurde angezeigt werden?
