### ISSUE TITLE
Spielplan (PH)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#5]
https://www.praegla.net/pinkie/public/news/clubSchedule.xhtml

wäre es evtl. möglich nicht nur die Gesamtliste anzubieten, sondern zusätzliche Filter darüber anzubieten, damit ich nach einem Spieltag filtern kann, oder nach einer Mannschaft?

**Comment by AlexanderPraegla** [comment]
hab jetzt mal so Suchboxen über allen Spalten hinzugefügt. Kam direkt im Framework mit. Allerdings funktioniert die Suche nicht mehr, wenn man bei einer Spalte die Suchbox entfernt. 

Eine Alternative wäre über der Tabelle ein eigenes kleines Formular zu erstellen über welches man suchen kann.
