### ISSUE TITLE
Fotogallerie (PH)  

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#6]
(als presse, teilweise als admin)

1. Übersicht ist gut, wenn ich allerdings ein Bild größer mache, wäre es schön, wenn ich auch in der Ansicht durchblättern könnte (vor/ zurück)

2. Hochkantbilder werden quer hochgeladen und eingefügt!   - ansonsten muss das kommuniziert werden, dass nur querformat hochgeladen werden darf
Wie sieht es mit Bildunterschriften aus? Möglich? als optional.
Bildgröße - welche Empfehlung gibt es für die Bilder?

3. Es lässt sich eine Gallerie nicht löschen? auch als admin nicht

4. Würde die Aktualität hier über die Datenbank machen - und ein Ablaufdatum von 12 Monaten hinterlegen - wäre das möglich?

5. Wie können einzelne Bilder in einer Gallerie gelöscht werden - wäre schön, wenn dies auch der Verfasser machen könnte - in der Übersicht mit markieren und dann löschen.

**Comment by AlexanderPraegla** [comment]
1. Ansicht zum Durchbättern ist mit JSFs gar nicht so leicht, müsste da ein großes Javascript gedöns einbauen und ich finde für die erste Version reicht das so erstmal. Es würde bestimmt irgendwie gehen, aber zu viel Zeit kosten.

2. Hochkantbilder: meine Vermutung ist, nur bei Bilder nicht geht, welche mit einem iPhone aufgenommen worden sind. Ich konnte selber ohne Probleme Bilder aus dem Internet im Hochkantformat hochladen. Das würde auch erklären wieso die Bilder der mA auf der aktuellen Homepage auch so falsch gedreht sind.

3. Gallerie kann nun archiviert werden und erscheint nicht mehr in der Übersicht.

4. Finde ich nicht schön, da man ja auch gerne mal die ganz alten Bilder anschauen will.

5. Einzelne Bilder können nun aus einem Album entfernt werden. Hier muss noch geklärt werden ob die wirklich gelöscht werden sollen. Aktuell werden sie nur aus der Datenbank entfernt und erscheinen somit nicht mehr im Album. Liegen allerdings noch auf der Festplatte des Servers.
