### ISSUE TITLE
Mannschaften (PH) 

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#7]
Tab: Spielplan - wäre ein Link auf die NuLiga zum detaillierten Spielbericht noch möglich ? 

Link zur NuLiga ist kaum wahrzunehmen, würde diesen auch ganz unten erst einfügen, es sind ja alle Details in den anderen Tabs zu finden 
___

als admin: 
Mannschaft anlegen: 
welche Datei soll bei 'Saison' hochgeladen werden?

Wollte Mannschaft anlegen - hatte nur keinen Link bei NuLiga eingegeben, nach dem drücken von Speichen  waren alle Felder leer und nichts wurde gespeichert.

**Comment by AlexanderPraegla** [comment]
1. Button ist bereits eingebaut. 

2. Sollte das Mannschaftsbild sein, hab ein Label hinzugefügt

3. Problem sollte behoben sein.

**Comment by AlexanderPraegla** [comment]
Ist erledigt
