### ISSUE TITLE
Anfahrt  (PH)

### ISSUE THREAD

**Issue by PinkieTester** [danielsagert/Pinkie#8]
https://www.praegla.net/pinkie/public/about/journey.xhtml

headline:  So findet Ihr uns    - Tippfehler drin!

wenn möglich auch google maps einbinden, für Routenplander

**Comment by AlexanderPraegla** [comment]
Typo verbessert.

Routenplaner habe ich ein neues Issue angelegt, da dies nicht sofort mit iFrames geht sondern bisl Aufwand ist.
